# Generated by Django 2.1.2 on 2018-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='college_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='issues_solved',
            field=models.IntegerField(default=0, verbose_name='issues_solved'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bio'),
        ),
    ]
