# Generated by Django 2.1.2 on 2018-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20181009_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='bonus_points'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deducted_points',
            field=models.IntegerField(default=0, verbose_name='deducted_points'),
        ),
    ]
