# Generated by Django 2.1.1 on 2018-09-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_issue', models.CharField(blank=True, max_length=40, null=True, verbose_name='title_issue')),
                ('link_issue', models.CharField(blank=True, max_length=200, null=True, verbose_name='link_issue')),
                ('title_project', models.CharField(blank=True, max_length=40, null=True, verbose_name='title_project')),
                ('link_project', models.CharField(blank=True, max_length=200, null=True, verbose_name='link_project')),
                ('level', models.IntegerField(default=1, verbose_name='level_issue')),
                ('points', models.IntegerField(default=0, verbose_name='points_for_issue')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'db_table': 'issues_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_such_prs', models.IntegerField(default=1, verbose_name='all_such_prs')),
                ('status', models.IntegerField(default=1, verbose_name='status_issue')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_creates_pr', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Issues')),
            ],
            options={
                'verbose_name': 'pr',
                'verbose_name_plural': 'prs',
                'db_table': 'prs_info',
                'managed': True,
            },
        ),
    ]
