# Generated by Django 2.1.1 on 2018-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_issue', models.CharField(blank=True, max_length=40, null=True, verbose_name='title_issue')),
                ('link_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='link_issue')),
                ('title_project', models.CharField(blank=True, max_length=40, null=True, verbose_name='title_project')),
                ('link_project', models.CharField(blank=True, max_length=200, null=True, verbose_name='link_project')),
                ('mentor', models.CharField(blank=True, max_length=40, null=True, verbose_name='mentor_issue')),
                ('level', models.IntegerField(default=1, verbose_name='level_issue')),
                ('status', models.IntegerField(default=0, verbose_name='status_issue')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'db_table': 'issues_info',
                'managed': True,
            },
        ),
    ]
