# Generated by Django 2.1.1 on 2018-09-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='link_title',
            new_name='link_issue',
        ),
    ]
