# Generated by Django 2.1.2 on 2018-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prs',
            name='pr_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pr_issue'),
        ),
    ]
