# Generated by Django 2.1.1 on 2018-09-01 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20180901_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
