# Generated by Django 2.1.1 on 2018-09-01 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20180901_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
