# Generated by Django 2.1.1 on 2018-09-02 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0004_auto_20180901_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_prs', models.IntegerField(default=1, verbose_name='all_such_prs')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_who_creates_pr', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.Issues')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_who_made_this_issue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pr',
                'verbose_name_plural': 'prs',
                'db_table': 'prs_info',
                'managed': True,
            },
        ),
    ]
