# Generated by Django 2.1.1 on 2018-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_prs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.IntegerField(default=1, verbose_name='status_issue'),
        ),
    ]
