# Generated by Django 2.1.1 on 2018-09-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20180902_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prs',
            name='mentor',
        ),
    ]
