# Generated by Django 2.1.1 on 2018-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_remove_prs_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='status',
        ),
        migrations.AddField(
            model_name='prs',
            name='status',
            field=models.IntegerField(default=1, verbose_name='status_issue'),
        ),
    ]
