# Generated by Django 2.1.1 on 2018-09-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20180902_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prs',
            old_name='all_prs',
            new_name='all_such_prs',
        ),
    ]
