# Generated by Django 2.1.1 on 2018-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20180902_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='points',
            field=models.IntegerField(default=0, verbose_name='points_for_issue'),
        ),
    ]
